### ISSUE TITLE
In executing the demos: cannot import name 'UMAP' from 'umap'

### ISSUE THREAD

**Issue by marcoippolito** [resemble-ai/Resemblyzer#6]
demo 01:

    (Resemblizer) (base) marco@pc:~/Resemblyzer$ python3 demo01_similarity.py 
    Traceback (most recent call last):
      File "demo01_similarity.py", line 2, in <module>
        from demo_utils import *
      File "/home/marco/Resemblyzer/demo_utils.py", line 6, in <module>
        from umap import UMAP
    ImportError: cannot import name 'UMAP' from 'umap' (/home/marco/Resemblyzer/Resemblizer 
    /lib/python3.7/site-packages/umap/__init__.py)

demo02 :  

    (Resemblizer) (base) marco@pc:~/Resemblyzer$ python3 demo02_diarization.py 
    Traceback (most recent call last):
      File "demo02_diarization.py", line 2, in <module>
        from demo_utils import *
      File "/home/marco/Resemblyzer/demo_utils.py", line 6, in <module>
        from umap import UMAP
    ImportError: cannot import name 'UMAP' from 'umap' (/home/marco/Resemblyzer/Resemblizer
    /lib/python3.7/site-packages/umap/__init__.py)

demo03:

    (Resemblizer) (base) marco@pc:~/Resemblyzer$ python3 demo03_projection.py 
    Traceback (most recent call last):
      File "demo03_projection.py", line 2, in <module>
        from demo_utils import *
      File "/home/marco/Resemblyzer/demo_utils.py", line 6, in <module>
        from umap import UMAP
    ImportError: cannot import name 'UMAP' from 'umap' (/home/marco/Resemblyzer/Resemblizer
    /lib/python3.7/site-packages/umap/__init__.py)

How to solve the problem?
Marco

**Comment by CorentinJ** [comment]
I've updated the requirements with the last push: https://github.com/resemble-ai/Resemblyzer/blob/master/requirements_demos.txt#L9

Just do `pip install umap-learn`

**Comment by marcoippolito** [comment]
Thanks!!!

**Comment by Shridharpawar77** [comment]
Use import umap.umap_ as UMAP
instead of from umap import UMAP
